site_name: O-RISC-V. Only RISC-V Resources
site_url: https://o-riscv.com
theme:
  logo: assets/o-riscv.png
  favicon: assets/o-riscv.png
  name: material
  palette:
    scheme: slate
    primary: blue grey
    accent: orange
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.indexes
    - toc.follow
plugins:
  - search
  - table-reader
  - social
  - bibtex:
      bib_file: "docs/assets/RISC-V.bib"
      csl_file: "https://raw.githubusercontent.com/citation-style-language/styles/master/ieee.csl"
markdown_extensions:
  - abbr
  - tables
  - admonition
  - attr_list
  - def_list
  - footnotes
  - toc:
      permalink: true
  - tables
  - pymdownx.tasklist
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra:
  analytics:
    provider: google
    property: G-KXWH4MD9EY
  social:
    - icon: fontawesome/brands/mastodon 
      link: infosec.exchange/@phretor
    - icon: fontawesome/brands/twitter
      link: twitter.com/@phretor
    - icon: fontawesome/brands/github
      link: github.com/phretor/o-riscv
    - icon: fontawesome/brands/linkedin
      link: linkedin.com/in/phretor
copyright: Copyright &copy; 2024 Federico Maggi & authors of linked resources.
repo_url: https://github.com/o-riscv/o-riscv
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
extra_css:
  - stylesheets/extra.css
